[default]
contracts = 'src/contracts'
gas_reports = ["*"]
libs = ['lib']
offline = true                # Disable downloading of missing solc version(s)
optimizer = true              # Enable or disable the solc optimizer
optimizer_runs = 200          # The number of optimizer runs
out = 'out'
src = 'src'
verbosity = 3                 # The verbosity of tests

fuzz_runs = 1000

[local]
fuzz_runs = 1000

[deep]
fuzz_runs = 20000

[super_deep]
fuzz_runs = 100000


# See more config options https://github.com/gakonst/foundry/tree/master/config